project:
  type: website

website:
  title: "Giovanni Forchini"
  google-analytics: "G-EW8G9TEY50"
  navbar:
    background: primary
    search: true
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/giovanni-forchini-77452794/
      - icon: twitter
        href: https://twitter.com/gforchini
      - icon: github
        href: https://github.com/gforchini
    left:
      - about.qmd
      - bio.qmd
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

