---
title: "A PhD thesis defense"
author: "Giovanni Forchini"
date: "2017-03-03"
---

Last Friday I attended my first PhD 'defense' in the Swedish system. It was definitely enjoyable and it was interesting to discover what Mattias, the 'defendant', has researched in the last few years.

The structure of the defense was as follows. Firstly the 'opponent', an established expert in the area, gave a general overview of the PhD research topic and put it into a context; secondly, he asked probing questions to the defendant - some of which were general and some very specific - which Mattias answer very confidently; thirdly the members of the grading committee - because the grade was decided by a three persons committee not by the opponent - and the public had the chance to ask further questions.

The defence was public. In fact it was attended by academics, colleagues, students, friends and family. It was a rite of passage very different from the UK viva - which I experienced directly and as an internal examiner- or by the Australian thesis submission - experienced through my PhD students.

The viva in the UK is a private matter between the candidate and the internal and external examiners. Although it can be certainly as intimidating as the 'defence', it is an individual rite of passage rather than a public one. I feel it reflects the the different ways in which education is perceived in the two countries: it is for the benefit of the individual in the UK but it is for the benefit of Society in Sweden. A fundamental difference.

In Australia the thesis is submitted and two external examiners write two independent reports on the thesis recommending the award of the PhD or a resubmission subject to either small corrections or, sometimes, fundamental changes and resubmission. There is no discussion with the examiners, and as a rite of passage, it is definitely subdued.

As a young  non conformist PhD student the latter would have been my favourite approach. But I have changed my mind as I got older. I have come to realise that a few rites of passage are important - not so much for the individuals undergoing them - but for all the others who observe them in order to accept them as part of a group and to recognise their accomplishments. What I liked most of the defence on Friday was the fact that a layperson could have a glimpse into the research life of Mattias, and could see the hard work, determination, skills, knowledge, frustrations, pragmatism, leadership, independence and teamwork that completing a PhD requires - and that would be summarised by a recruiter as 'proficient in stata'.