---
title: "Computing exact distributions"
author: "Giovanni Forchini"
date: "2023-08-24"
---

# Introduction

The computation of exact distributions relies on a set of techniques that do not seem to be part of the modern econometrician's toolbox. Here and in the next few blog articles will review these techniques, but before I will try to persuade the reader that this is worth doing.

Improvements in the computer speed and memory allow a researcher to simulate almost every conceivable distribution. So, why should I try to derive these distributions analytically? There are several reasons.

First, by calculating exact distributions I may be able to deduce properties of estimators and tests that are not immediately obvious. For example, I may find that the distribution of the statistics of interest depends on some specific parameters only, or on a certain function of the parameters. I can use this knowledge to improve simulations designs, and make them faster and more efficient.

Second, calculating exact distribution may emphasise aspects of the distribution that cannot be picked up by using simulations. For example, it was common in the econometric literature of the 1970s to compare estimators of the coefficient of the endogenous variables in linear structural equations by comparing their moments. However, for a common estimator, the LIML, these do not exist.

Third, knowledge of the exact distribution can be very useful for generating random numbers in simulations based methods. Here the problem is that of generating random variables having a specified distribution: common algorithms, such as the "accept-reject method" and modification thereof require the knowledge of the exact distribution of the random variable one wants to generate. In the multivariate case, knowledge of some exact distribution theory can make the algorithms computationally efficient.

Exact distribution can often be used in conjunction with asymptotic theory. The weakly identified structural equations models are an example of this. Here one finds that under weak instrument the asymptotic distribution of the usual estimator of the coefficients of the endogenous variables in a structural equation model formally almost the same as their exact distributions under the assumption of normal errors.

The aim of this and the following few blog articles is to acquaint the reader with the main techniques that have been used or that are currently used for the evaluation of exact distributions.
